[package]
name = "aviutl2-catalog"
version = "0.1.5"
description = "AviUtl2 Catalog"
authors = ["Neosku"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-http = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
zip = { version = "6", default-features = false, features = ["deflate"] }
once_cell = "1"
time = { version = "0.3", features = ["parsing", "formatting"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
sha2 = "0.10"
reqwest = { version = "0.12", default-features = false, features = ["native-tls", "gzip", "deflate", "blocking"] }
url = "2"
thiserror = "2"
arc-swap = "1"
dirs-next = "2"
walkdir = "2"
sevenz-rust2 = "0.19"
memmap2 = "0.9"
memchr  = "2"
encoding_rs = "0.8"
windows = { version = "0.62", features = [
  "Win32_Foundation",
  "Win32_UI_WindowsAndMessaging",
  "Win32_System_LibraryLoader",
  "Win32_System_Threading",
  "Win32_Graphics_Gdi", 
] }
anyhow = "1"
tokio = { version = "1", features = ["full"] }
[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
