# 1行の最大幅（デフォルトは 100）
max_width = 180
chain_indent = "Visual"
use_small_heuristics = "Max"

# 関数呼び出しの引数の折り返しをなるべく避ける
fn_call_width = 180
single_line_fn_args = true

# 構造体やタプルのフィールドもできるだけ1行に
struct_lit_width = 80
array_width = 80

# メソッドチェーンをなるべく1行にまとめる
chain_width = 180